name: example
description: A new Flutter project.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.12.2
  implicitly_animated_reorderable_list: ^0.2.5
  material_design_icons_flutter: ^4.0.5345
  material_floating_search_bar:
    path: ../
  provider: ^4.3.1
  sliding_sheet: ^0.3.7

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/map.jpg
  
  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat/Montserrat-SemiBold.ttf
          weight: 500
        - asset: assets/fonts/Montserrat/Montserrat-ExtraBold.ttf
          weight: 600
        - asset: assets/fonts/Montserrat/Montserrat-Black.ttf
          weight: 700
